# Generated by Django 4.2 on 2023-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_comentcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заявки'),
        ),
    ]
